tweetproject/tweetproject/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', include('tweets.urls')),
    url(r'^tweets/', include('tweets.urls', namespace="tweets")),
    url(r'^admin/', include(admin.site.urls)),
)

tweetproject/tweets/urls.py
from django.conf.urls import patterns, url

from tweets import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^search/$', views.search, name="search"),
    url(r'^user/(?P<username>\w{0,50})/$', views.user, name="user"),
)

tweetproject/tweets/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.
from __future__ import unicode_literals
import datetime 
from datetime import date
from django.utils import timezone
from ttp import ttp
from datetime import timedelta

from django.db import models

class Tweets(models.Model):
    tweet_id = models.IntegerField(primary_key=True)
    twitter_tweet_id = models.CharField(max_length=200, blank=True)
    text = models.CharField(max_length=300, blank=True)
    user = models.CharField(max_length=200, blank=True)
    date = models.CharField(max_length=100, blank=True)
    class Meta:
        db_table = 'tweets'

    def __unicode__(self):
        return self.user + ' : ' + self.text

    def is_today(self):
        return date.fromtimestamp(self.date/1000.0) >  date.today() - timedelta(days=1)
    
    def text_as_html(self):
        p = ttp.Parser()
        result = p.parse(self.text)
        return result.html

    def hashtags(self):
        p = ttp.Parser()
        result = p.parse(self.text)
        hashlist = result.tags;
        l = list()
        for f in hashlist:
            l.append(str("#"+f))
        return l

class User(models.Model):
    username = models.CharField(max_length=50, blank=False)
    profilepicture = models.CharField(max_length=200, blank=True)
    location = models.CharField(max_length=200, blank=True)
    description = models.CharField(max_length=500, blank=True)
    language = models.CharField(max_length=100, blank=True)
    url = models.CharField(max_length=300, blank=True)
    fav_count = models.IntegerField(blank=True)
    followers_count = models.IntegerField(blank=True)
    friends_count = models.IntegerField(blank=True)
    date_created = models.CharField(max_length=100, blank=True)

    class Meta:
        db_table = 'users'

    def __unicode__(self):
        return str(self.username)

class Search(models.Model):
    searchtext = models.CharField(max_length=200, blank=False)
    searchdate = models.DateTimeField(auto_now_add=True)
    class Meta:
        db_table = 'searches'

    def __unicode__(self):
        return str(self.searchtext)

tweetproject/tweets/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import time
from time import mktime
from datetime import timedelta
from datetime import date
from ttp import ttp
import collections

from tweets.models import Tweets, User, Search

# Create your views here.

def index(request):
    latest_tweets_list = Tweets.objects.all().order_by('-date')[:8]

#    date = datetime.date.today()
 #   start_week = date - datetime.timedelta(date.weekday())
  #  end_week = start_week + datetime.timedelta(7)
   # entries = Tweets.objects.filter(created_at__range=[start_week, end_week])latest_tweets_list

    today = datetime.date.today()
    today = today - datetime.timedelta(days=today.weekday())
    this_weeks_tweets = Tweets.objects.filter(date__gte=int(time.mktime(today.timetuple())*1000))

    last_five_searches = Search.objects.all().order_by('-searchdate')[:5]
    
    most_common = find_most_tweeter(this_weeks_tweets)
    
    chart_array = loop_through_week(this_weeks_tweets)
    
    context = {'latest_tweets_list': latest_tweets_list, 'chart_array': chart_array, 'amount_of_tweets': len(Tweets.objects.all()), 'most_common': most_common, 'searches': last_five_searches}
    return render(request, 'tweets/index.html', context)

def search(request):
    person_filter_term = request.GET.get('personfilter');
    search_term = request.GET.get('search_term')

    results = Tweets.objects.all()

    search = Search(searchtext=search_term).save()

    if search_term is not None and search_term != '':
        results = results.filter(text__icontains=search_term)
    
    if person_filter_term is not None and person_filter_term != '':
        results = results.filter(user=person_filter_term)
    
    # unique_users = results.values_list('user', flat=True);
    unique_users = User.objects.all();

    search_size = len(results)

    paginator = Paginator(results, 15)

    page = request.GET.get('page')
    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        results = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        results = paginator.page(paginator.num_pages)

    context = {'results': results, 'search_term': search_term, 'usernames': set(unique_users), 'amount_of_tweets': len(Tweets.objects.all()), 'search_size': search_size}
    return render(request, 'tweets/search/result.html', context)

def user(request, username):

    result = User.objects.all().filter(username=username)
    
    results  = Tweets.objects.all().filter(user=username).order_by('-date')
    paginator = Paginator(results, 10)

    page = request.GET.get('page')
    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        results = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        results = paginator.page(paginator.num_pages)

    today = datetime.date.today()
    today = today - datetime.timedelta(days=today.weekday())
    this_weeks_tweets = Tweets.objects.filter(user=username).filter(date__gte=int(time.mktime(today.timetuple())*1000))
    chart_array = loop_through_week(this_weeks_tweets)

    context = {'results': results, 'result': result.get(), 'username': username, 'latest_tweets_list': results, 'chart_array': chart_array}
    return render(request, 'tweets/user/user.html', context)
    

def loop_through_week(tweet_list):
    count = 0
    my_list = list()
    today = date.today()
    for x in range(0, 7):
        offset = (today.weekday() - x) %7
        last_day = today - timedelta(days=offset)
        # print last_day
        for o in tweet_list:
            if date.fromtimestamp(o.date/1000.0) == last_day:
                count = count + 1
        my_list.append(count)
        count = 0
    return my_list
    
def find_most_tweeter(tweet_list):
    users = tweet_list.values_list('user', flat=True)
    counter = collections.Counter(users)
    return counter.most_common()

tweetproject/tweets/templates/tweets/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
{% include "tweets/modules/head_snippet.html" %}
<body>
  <div class="container">
    {% include "tweets/modules/search_box_snippet.html" %}
    <div class="container-fluid">
      <div class="row">
       <div class="col-md-6">
        {% include "tweets/modules/newest_tweets.html" with latest_tweets_list=latest_tweets_list %}
       </div>
       <div class="col-md-6">
        {% include "tweets/modules/most_active_d_of_w.html" with chart_array=chart_array %}
        {% include "tweets/modules/most_recent_searches.html" with searches=searches %}
      </div>
    </div>
  </div>

</div><!-- /.container -->


</body>
</html>

tweetproject/tweets/templates/tweets/modules/head_snippet.html
{% load staticfiles %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>CFC Tweet-Analysis</title>

    <script src="{% static "tweets/js/Chart.js" %}"></script>

    <!-- Bootstrap core CSS -->
    <link href="{% static "tweets/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "tweets/css/ownstyle.css" %}" rel="stylesheet">    
</head>

tweetproject/tweets/templates/tweets/modules/most_active_d_of_w.html
<div>
	<h3>Most active day this week</h3>
	<canvas id="myChart" width="auto" height="auto"></canvas>
    <script type="text/javascript">
        Chart.defaults.global.responsive = true;
        var data = {
    	      labels: ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],
              datasets: [
                  {
                      label: "My Second dataset",
                      fillColor: "rgba(151,187,205,0.5)",
                      strokeColor: "rgba(151,187,205,0.8)",
                      highlightFill: "rgba(151,187,205,0.75)",
                      highlightStroke: "rgba(151,187,205,1)",
                      data: {{ chart_array }}
                  }
              ]
          };
        var ctx = document.getElementById("myChart").getContext("2d");
        var myNewChart = new Chart(ctx).Bar(data);
    </script>
</div>

tweetproject/tweets/templates/tweets/modules/most_recent_searches.html
<div>
  <h3>Most recent searches</h3>
    {% for search in searches %}
      <a href="#" class="list-group-item">
        <p class="list-group-item-text">{{ search.searchtext }}</p>
        <p class="list-group-item-text">{{ search.searchdate }}</p>
      </a>
    {% endfor %}
</div>

tweetproject/tweets/templates/tweets/modules/newest_tweets.html
<div>
	<h3>Newest tweets</h3>
	<div class="list-group">
		{% for tweets in latest_tweets_list %}
		<a href="/tweets/user/{{ tweets.user }}" class="list-group-item">
			{% if tweets.is_today %}
			<span class="badge pull-right">today!</span>
			{% endif %}
			<h4 class="list-group-item-heading">{{ tweets.user }}</h4>
			<p class="list-group-item-text">{{ tweets.text }}</p>
		</a>
		{% endfor %}
	</div>
</div>

tweetproject/tweets/templates/tweets/modules/search_box_snippet.html
{% load staticfiles %}

      <div class="starter-template">
        <a href="/"><h1 style="font-size:58px">CHELSEA FC TWEET ANALYSIS</h1></a>
        <p class="lead">The database contains <i>{{amount_of_tweets}}</i> tweets of Chelsea FC players.</p>

        <form action="{% url 'tweets:search' %}" method="get">
        {% csrf_token %}
            <input name="search_term" id="search_term" class="form-control input-lg" type="text" placeholder="enter any search term here, like '#CFC' or 'Petr Cech + Pizza'" value="{{ search_term }}">
        </form>
      </div>

tweetproject/tweets/templates/tweets/modules/user_summary.html
<div>
	<h3>{{ user.username }}</h3>
	<img src="{{ user.profilepicture }}" class="img-responsive" alt="Responsive image">
	<dl>
		<dt>username</dt>
		<dd>{{ user.username }}</dd>
		<dt>description</dt>
		<dd>{{ user.description }}</dd>
		<dt>location</dt>
		<dd>{{ user.location }}</dd>
	</dl>
</div>

tweetproject/tweets/templates/tweets/search/result.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
{% include "tweets/modules/head_snippet.html" %}
  <body>
    <div class="container">
      {% include "tweets/modules/search_box_snippet.html" with amount_of_tweets=amount_of_tweets search_term=search_term %}
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-4">
            <h3>Conclusion</h3>
            <p>there are <b>{{ search_size }}</b> tweets for your search</p>
            <h3>Filters</h3> 
            <h4>by player</h4>
            {% for user in usernames %}
              <form action="{% url 'tweets:search' %}" method="get">
                <div class="checkbox">
                  <label>
                    <input onClick="this.form.submit();" name="personfilter" id="filter_p_{{ forloop.counter }}" value="{{ user }}" type="radio"> {{ user }}
                  </label>
                  <input name="search_term" type="hidden" value="{{ search_term }}"></input>
                </div>
              </form>
            {% endfor %}
          </div>
          <div class="col-md-8">
          {% if results %}
                {% for result in results %}
                 <a href="/tweets/user/{{ result.user }}" class="list-group-item">
                  {% if result.hashtags %}
                   <span class="badge pull-right">{{ result.hashtags|length }} hashtags</span>
                   {% endif %}
                   <h4 class="list-group-item-heading">@{{ result.user }}</h4>
                   <p class="list-group-item-text">{{ result.text }}</p>
                   <p class="list-group-item-text">{% for hashtag in result.hashtags %} {{ hashtag }} {% endfor %}</p>
                 </a>
                {% endfor %}
            <div class="pagination">
              <span class="step-links">
                  {% if results.has_previous %}
                      <a href="?page={{ results.previous_page_number }}&search_term={{ search_term }}">previous</a>
                  {% endif %}

                  <span class="current">
                      Page {{ results.number }} of {{ results.paginator.num_pages }}.
                  </span>

                  {% if results.has_next %}
                      <a href="?page={{ results.next_page_number }}&search_term={{ search_term }}">next</a>
                  {% endif %}
              </span>
            </div>
          {% else %}
                <p>No tweets are available :(.</p>
           {% endif %}
         </div>
        </div>
      </div>
    </div>
  </body>
</html>

tweetproject/tweets/templates/tweets/user/user.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
{% include "tweets/modules/head_snippet.html" %}
<body>
  <div class="container">
    {% include "tweets/modules/search_box_snippet.html" %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-4">
          {% include "tweets/modules/user_summary.html" with user=result %}
          {% include "tweets/modules/most_active_d_of_w.html" with chart_array=chart_array %}
        </div>
        <div class="col-md-8">
          {% include "tweets/modules/newest_tweets.html" with latest_tweets_list=latest_tweets_list %}
          <div class="pagination">
            <ul class="pager">
              {% if results.has_previous %}
              <li class="previous"><a href="?page={{ results.previous_page_number }}&search_term={{ search_term }}">previous</a></li>
              {% endif %}
              {% if results.has_next %}
              <li class="next"><a href="?page={{ results.next_page_number }}&search_term={{ search_term }}">next</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </div>

  </div>
</body>
</html>